services:
  - type: web
    name: backgammon-news
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: PORT
        value: 10000
